name: superdiff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - jax[cuda12_pjrt]==0.4.28
      - jaxlib==0.4.28+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - flax==0.9.0
      - equinox==0.11.3
      - diffrax==0.6.0
      - optax==0.2.3
      - orbax-checkpoint==0.6.4
      - lineax==0.0.5
      - ml-dtypes==0.4.1
      - chex==0.1.86
      - jaxtyping==0.2.34
      - matplotlib==3.9.2
      - scipy==1.14.1
      - numpy==1.26.4
      - opt-einsum==3.3.0
      - toolz==0.12.1
      - tensorboard==2.17.1
      - tensorflow==2.17.0
      - tensorflow-datasets==4.9.6
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.15.0
      - fsspec==2024.9.0
      - protobuf==3.20.3
      - pyarrow==17.0.0
      - h5py==3.11.0
      - wandb==0.18.1
      - requests==2.32.3
      - tqdm==4.66.5
      - typing_extensions==4.12.2
      - Pillow==10.4.0
      - absl-py==2.1.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - docstring_parser==0.16
      - simple-parsing==0.1.6
      - dm-tree==0.1.8
      - ml_collections==0.1.1
      - humanize==4.10.0
      - jupyter
      - ipykernel
      - ipython
      - notebook
      - rich
